title: Joseph Pascual
logo: "/images/IMG_4582.jpg?raw=true"
description: > 
  ⚕️ Music Marketing to Health Care Analyst
  <br><br>
  💻 Excel, Tableau, SQL, Python, R
  <br><br>
  🛹 I can kickflip
  <br><br>
  📍 Sacramento, CA <-> San Francisco, CA
  <br><br>
  <a href="https://www.linkedin.com/in/josephpascual/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: G-X38M2NHY95
